name: Run Java Program

on:
  push:            # Déclenchement automatique à chaque modification
    branches: [ "main" ]
  workflow_dispatch:  # Permet de le lancer manuellement

jobs:
  run-java:
    runs-on: ubuntu-latest   # Machine Linux virtuelle

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run HelloWorld.java
        run: |
          javac HelloWorld.java
          java HelloWorld
